plugins {
	id("fabric-loom") version("${loom_version}")
	id("maven-publish")
    id("me.modmuss50.mod-publish-plugin") version("${mpp_version}")
    id("org.ajoberstar.grgit.service") version("${grgitservice_version}")
}

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
    maven {
        name = "Bawnorton"
        url = "https://maven.bawnorton.com/releases"
    }
    maven {
        name = "Modrinth"
        url = uri("https://api.modrinth.com/maven")
    }
    maven {
        name = "uku"
        url = "https://maven.uku3lig.net/releases"
    }
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"armor-hud-numbers" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // MixinSquared
    include(implementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-fabric:${project.mixinsquared_version}")))

    // uku's Armor HUD
    modImplementation "maven.modrinth:wF189hn9:${project.armorhud_version}"
    // ukulib
    modImplementation "net.uku3lig:ukulib:${project.ukulib_version}"
}

processResources {
    final expandProps = [
            "version": project.version,
            "loader_versions": project.loader_versions,
            "minecraft_versions": project.minecraft_versions,
            "java_versions": project.java_versions,
            "armorhud_versions": project.armorhud_versions,
    ]

	filesMatching("fabric.mod.json") {
		expand(expandProps)
	}
    inputs.properties(expandProps)
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE.txt") {
		rename { "LICENSE_${inputs.properties.archivesName}.txt"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}

publishMods {
    file = remapJar.archiveFile
    version = "${mod_version}+${minecraft_version}"
    type = STABLE
    displayName = "v${mod_version}+${minecraft_version}"
    modLoaders.add("fabric")

    github {
        accessToken = providers.environmentVariable("GITHUB_TOKEN")
        repository = "NotRyken/armor-hud-numbers"
        commitish = grgitService.service.get().grgit.branch.current().name
        tagName = "v${mod_version}+${minecraft_version}"
        changelog = "[Changelog](./changelog.md#${mod_version.replaceAll("\\.", "")})"
        additionalFiles.from(sourcesJar.archiveFile)
    }

    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_API_KEY")
        projectId = "e74hc5Bq"
        minecraftVersions.addAll(project.property("modrinth_versions").toString().split(",")
                .findAll { !it.isBlank() }
                .collect { it.strip() })
        changelog = versionChangelog(rootProject.file("changelog.md"), mod_version)
        requires {
            id = "wF189hn9" // uku's Armor HUD
        }
        requires {
            id = "Y8uFrUil" // ukulib
        }
        requires {
            id = "P7dR8mSH" // Fabric API
        }
        projectDescription = providers.fileContents(layout.projectDirectory.file("README.md")).asText
    }
}

static String versionChangelog(File file, String version) {
    final lines = file.readLines()
    final builder = new StringBuilder()
    // Changelog version header is on the third line of the file; check it
    if (version != lines.get(2).substring(3)) {
        throw new IllegalArgumentException(String.format(
                "Mod version '%s' does not match changelog version '%s'",
                version,
                lines.get(2).substring(3)
        ))
    } else {
        // Iterate over content lines
        for (int i = 4; i < lines.size(); i++) {
            final line = lines.get(i)
            if (line.startsWith("## ")) {
                // Encountered next changelog header; finish
                break
            } else {
                // Append the content line, respecting blank lines
                if (!builder.isEmpty()) builder.append("\n")
                if (!line.isBlank()) builder.append(line)
            }
        }
    }
    return builder.toString()
}
