# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties https://fabricmc.net/develop
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.2
loader_version=0.17.3
loom_version=1.11-SNAPSHOT

# Fabric API
fabric_version=0.136.0+1.21.10

# Mod Properties
mod_version=1.1.0
maven_group=com.notryken
archives_base_name=armor-hud-numbers
modrinth_versions=1.21.9,1.21.10

# Mod Dependencies
# MixinSquared https://github.com/Bawnorton/MixinSquared/releases
mixinsquared_version=0.3.3
# uku's Armor Hud https://modrinth.com/project/wF189hn9/versions
armorhud_version=h3thCvUO
# ukulib https://maven.uku3lig.net/#/releases/net/uku3lig/ukulib
ukulib_version=1.9.0+1.21.9

# Build Dependencies
# Mod Publish Plugin https://plugins.gradle.org/plugin/me.modmuss50.mod-publish-plugin
mpp_version=1.0.0
# grgit-service https://github.com/ajoberstar/grgit/releases
grgitservice_version=5.3.2

# FMJ Dependency Ranges
loader_versions=>=0.16.4
minecraft_versions=>1.21.8
java_versions=>=21
armorhud_versions=*
